spring:
  application:
    name: estate-biz
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
    sender:
      type: web
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    sampler:
      probability: 0.2


rocketmq:
  nameServer: "192.168.2.6:9876"
  producer:
    groupName: "pg1"

#morrow:
#  schedule:
feign:
  httpclient:
    connection-timeout: 5000
  hystrix:
    enabled: true
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ReadTimout: 60000
  ConnectTimeout: 60000
#    server-lists: localhost:2181,localhost:2182,localhost:2183

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}