spring:
  profiles:
    active: dev #默认为开发环境
  jackson:
    time-zone: "GMT+8"
    date-format: "yyyy-MM-dd HH:mm:ss"
  main:
    allow-bean-definition-overriding: true

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头


logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.jet.realestate.biz: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
server:
  port: 5050
