spring:
  application:
    name: estate-basic
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_basic?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: jet
    password: 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      pool-name: order-pool
      max-lifetime: 28740000
  zipkin:
    base-url: http://127.0.0.1:9411/
    discoveryClientEnabled: false
    sender:
      type: web
    service:
      name: ${spring.application.name}
  sleuth:
    enabled: true
    sampler:
      probability: 0.2